### PR TITLE
 Refactor inputs to support docker/metadata-action

### PR DESCRIPTION
**Pull request by ntkme**
This PR adds support for docker/metadata-action@v2. See https://github.com/redhat-actions/buildah-build/issues/74 and https://github.com/redhat-actions/buildah-build/pull/76.

### Description

Support tags input in full image name form. When full image name form is used, input image and input registry would be ignored.

### Related Issue(s)

https://github.com/redhat-actions/buildah-build/issues/74
https://github.com/redhat-actions/buildah-build/pull/76

### Checklist

- [x] This PR includes a documentation change
- [ ] This PR does not need a documentation change
---
- [x] This PR includes test changes
- [ ] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [ ] This change is a patch change
- [x] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

Support docker/metadata-action

### CODE REVIEW

**Comment by tetchel** [comment]
It would be great if we could capture this logic into one location, though I understand you are just working with the way it was written already.

image

**Comment by ntkme** [comment]
The issue with having same full image name tag on both docker and podman has been fixed by introducing a temporary storage `--root`. The `--storage-opts`' logic is copied from buildah action.

Looking at the action run on my fork, it appears everything now function correctly except that my fork failed to push images due to lack of credentials.

**Comment by divyansh42** [comment]
> During the test I found a bug where occasionally the `Created` timestamp from podman/docker images becomes `NaN`. It is due to [actions/toolkit#773](https://github.com/actions/toolkit/pull/773), so that I updated `@actions/exec` to latest.
> 
> Here is an example of this bug: https://github.com/redhat-actions/push-to-registry/runs/3833643212?check_suite_focus=true
> 
> In the screenshot you can see that supposedly podman's timestamp is later, but the output is saying docker's timestamp is later:
> 
> Screenshot 2021-10-08 12 02 24 AM

Thanks for bringing this up.
Just now I tested this behaviour, I have updated the `@actions/exec` to the latest version but I am still getting `NaN`. Don't know if they have tried to fix that in latest version.
Here is the workflow run with the updated dependency: https://github.com/redhat-actions/push-to-registry/runs/3837698262?check_suite_focus=true#step:6:113

**Comment by ntkme** [comment]
@divyansh42 Looking at the commit history for test branch, `dist/index.js` is still compiled with the old version. Also, the bundle check did not pass: https://github.com/redhat-actions/push-to-registry/runs/3837819085?check_suite_focus=true

I think you probably forgot the pre-commit hook?

**Comment by divyansh42** [comment]
> `podman system reset` was a bad idea as it cleared auth file created by login action. Now replaced with `podman rmi -a`, which should not have such side effect.

Yeah, it cleared the auth file, just about to say that.

**Comment by ntkme** [comment]
Forgot the pre-commit hook. Let me update it.

**Pull request merged**
