### PR TITLE
[FIX] Don't add docker.io prefix to ECR images

### PR DESCRIPTION
**Pull request by der-eismann**
### Description

The [action assumes](https://github.com/redhat-actions/push-to-registry/blob/main/src/util.ts#L81-L90) that if `image.split("/").length == 2`, the image must be from Docker hub instead of e.g. quay.io, where the value would be 3 (for example for quay.io/foreman/foreman:3.2-stable). But for AWS ECR (e.g. `123456789101.dkr.ecr.eu-west-1.amazonaws.com/example-project:master`) the value is also 2, so it adds the prefix even though it is not needed which breaks the action.

### Related Issue(s)

#68 

### Checklist

- [ ] This PR includes a documentation change
- [X] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [ ] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [X] This change is a patch change
- [ ] This change is a minor change
- [ ] This change is a major (breaking) change

### Changes made

- Don't add docker.io prefix to ECR images pulled from Docker daemon

### CODE REVIEW

**Comment by der-eismann** [comment]
I can confirm that this branch fixes our problems with the breaking builds. It would still be nice to disable the docker stuff altogether, but this is more important now.

**Comment by der-eismann** [comment]
@divyansh42 Can you provide any feedback on this PR?

**Comment by der-eismann** [comment]
@divyansh42 can you please get this in as well?

**Review by divyansh42 — APPROVED** [review]
Thanks @der-eismann for your PR!

**Comment by divyansh42** [comment]
@der-eismann could you please force push again? So that we can run the checks.

**Comment by divyansh42** [comment]
> I think you need to approve the workflows first before they run

For some reason, earlier I was not able to see that option. 
Now it is there. approved the workflow run.

**Comment by der-eismann** [comment]
Thank you for merging!

**Pull request merged**
